### ISSUE TITLE
https://github.com/orgs/COE11-USTP-CEA/projects/3#card-1746564

### ISSUE THREAD

**Issue by danbacs** [COE11-USTP-CEA/Passible#1]
any comment about the codes and the design. please clone the repo and unzip the file.

**Comment by melowcuesta** [comment]
@killertilapia  sir anything   comment or suggestion  about the  project? @

**Comment by melowcuesta** [comment]
@Christine-bannister @venoya04 @ROYDMACAPAGAL comment guys.
