### ISSUE TITLE
This is wrong

### ISSUE THREAD

**Issue by killertilapia** [COE11-USTP-CEA/Passible#2]
The plan was to clone the https://github.com/COE11-USTP-CEA/demospark repo and then do the changes, adding the landing page there.

The team didn't clone the demoSpark repo.

Also, why is there are a rar file in this repo?

**Comment by danbacs** [comment]
okay sir .  the changes will be posted later. @killertilapia

**Comment by danbacs** [comment]
@killertilapia sir we already upload the file sir.

**Comment by killertilapia** [comment]
This repo is still not to the standard found on the demoSpark repo. 

It still has extra file in the wrong places.

Clean this repo up and get it to the standard similar to the demoSpark repo OR risk another low score.

**Comment by melowcuesta** [comment]
okay sir
