### ISSUE TITLE
Why did you commit the target folder?

### ISSUE THREAD

**Issue by killertilapia** [COE11-USTP-CEA/Passible#4]
Why did you commit the target folder? It contains .class files which I have said not to include in the repo.

Why?

**Comment by ROYDMACAPAGAL** [comment]
sorry sir. i thought sir included siya.

**Comment by ROYDMACAPAGAL** [comment]
e delete nalng namu siya.

**Comment by melowcuesta** [comment]
done sir.

**Comment by killertilapia** [comment]
Ok.
